# Generated by Django 5.2.7 on 2025-10-28 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_profile_community_alter_profile_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'communities'},
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.country'),
        ),
        migrations.AddField(
            model_name='event',
            name='targeted_communities',
            field=models.ManyToManyField(blank=True, related_name='targeted_events', to='events.community'),
        ),
    ]
