# Generated by Django 5.2.7 on 2025-10-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_organizers'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
