# Generated by Django 5.2.7 on 2025-10-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_community_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Optional end date for the recurrence', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1, help_text='Interval for recurrence (e.g., every N days/weeks/months)'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_pattern',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
    ]
