# Generated by Django 5.2.7 on 2025-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_recurrence_end_date_event_recurrence_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='timezone',
            field=models.CharField(blank=True, help_text='IANA timezone name, e.g. "Asia/Tehran"', max_length=64, null=True),
        ),
    ]
