# Generated by Django 5.2.7 on 2025-11-02 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_country_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='timezone',
        ),
    ]
