# Generated by Django 5.2.7 on 2025-11-09 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_recurrence_interval_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
